/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import form.teknisi;

/**
 *
 * @author Aria
 */
public class menuutama extends javax.swing.JDialog {

    /**
     * Creates new form menuutama
     */
    public menuutama(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menupelanggan = new javax.swing.JMenu();
        menupelangganbaru = new javax.swing.JMenuItem();
        menucetakpelanggan = new javax.swing.JMenuItem();
        menuteknisi = new javax.swing.JMenu();
        menuteknisibaru = new javax.swing.JMenuItem();
        menucetakteknisi = new javax.swing.JMenuItem();
        menuharga = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        menupelanggan.setText("PELANGGAN");

        menupelangganbaru.setText("Pelanggan Baru");
        menupelangganbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupelangganbaruActionPerformed(evt);
            }
        });
        menupelanggan.add(menupelangganbaru);

        menucetakpelanggan.setText("Cetak");
        menupelanggan.add(menucetakpelanggan);

        jMenuBar1.add(menupelanggan);

        menuteknisi.setText("TEKNISI");

        menuteknisibaru.setText("Teknisi Baru");
        menuteknisibaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuteknisibaruActionPerformed(evt);
            }
        });
        menuteknisi.add(menuteknisibaru);

        menucetakteknisi.setText("Cetak");
        menuteknisi.add(menucetakteknisi);

        jMenuBar1.add(menuteknisi);

        menuharga.setText("HARGA");
        jMenuBar1.add(menuharga);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menupelangganbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupelangganbaruActionPerformed
        // TODO add your handling code here:
        new pelanggan().setVisible(true);
    }//GEN-LAST:event_menupelangganbaruActionPerformed

    private void menuteknisibaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuteknisibaruActionPerformed
        // TODO add your handling code here:
        new teknisi().setVisible(true);
    }//GEN-LAST:event_menuteknisibaruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                menuutama dialog = new menuutama(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menucetakpelanggan;
    private javax.swing.JMenuItem menucetakteknisi;
    private javax.swing.JMenu menuharga;
    private javax.swing.JMenu menupelanggan;
    private javax.swing.JMenuItem menupelangganbaru;
    private javax.swing.JMenu menuteknisi;
    private javax.swing.JMenuItem menuteknisibaru;
    // End of variables declaration//GEN-END:variables
}
